# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(f9ab245f-aa1a-4ca8-81a6-f6b216ccfb7a)'
    appType: 'webAppContainer'
    WebAppName: 'weather-appp1111'
    DockerNamespace: 'docker.io'
    DockerRepository: 'dipugodocker/weatherapp'
    DockerImageTag: 'v3'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
