apiVersion : apps/v1
kind: Deployment
metadata:
  name: "demok8s-8fb6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demok8s-8fb6"
  template:
    metadata:
      labels:
        app: "demok8s-8fb6"
    spec:
      containers:
        - name: "demok8s-8fb6"
          image: "dipankar.azurecr.io/demok8s"
          ports:
          - containerPort: 80