apiVersion: v1
kind: Service
metadata:
    name: "weather-svc"
    labels:
        app: "weather-svc"
    namespace: weather
spec:
    type: LoadBalancer
#     externalIPs:
#     - 192.168.49.2
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "weatherapp"
